# -*- coding: utf-8 -*-
"""AutoEmail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7_bG5SN9g3-DnMb1Rfr64dR2JRyIL28
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email import encoders
import datetime
import pytz

today = datetime.date.today()
dhaka_timezone = pytz.timezone("Asia/Dhaka")

# Email configuration
sender_email = 'anasamimulahasun@gmail.com'
sender_password = 'wbegxjinlzjmwfzt'
receiver_email = 'almehady@gmail.com'
bcc_email='anas180498@gmail.com'
date = datetime.datetime.now()
subject = "Histogram report of Covid Deaths & Confirmed Death-" + str(today)
message =  " Dear Sir, \n\n.I sent the attachmement of histrogram Covid Deaths & Confirmed Death \n\n MD. Amimul Ahasun Anas\n Data Analyst\n ADN Diginet\n"+" "+datetime.datetime.now(dhaka_timezone).strftime("%H:%M:%S")

# Create the email message
msg = MIMEMultipart()
msg['From'] = sender_email
msg['To'] = receiver_email
msg['Bcc'] = bcc_email
msg['Subject'] = subject

msg.attach(MIMEText(message, 'plain'))
# Attach the histogram.png file
with open('Histogram(ConfirmedDeath).png', 'rb') as file:
    image = MIMEImage(file.read(), name='Histogram(ConfirmedDeath).png')
    msg.attach(image)
with open('Histogram(Death).png', 'rb') as file:
    image = MIMEImage(file.read(), name='Histogram(Death).png')
    msg.attach(image)
# Connect to the SMTP server and send the email
with smtplib.SMTP(host='smtp.gmail.com', port=587) as server:
    server.starttls()
    server.login(sender_email, sender_password)
    server.send_message(msg)